### ISSUE TITLE
Your connection is not private

### ISSUE THREAD

**Issue by zen37** [cloudnativedevops/blog#32]
Clicked on the link https://cloudnativedevopsblog.com/ and got:

```
Your connection is not private
Attackers might be trying to steal your information from cloudnativedevopsblog.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
```

**Comment by bitfield** [comment]
Thanks for your interest, but that site no longer exists—there wasn't much traffic on it, and it was costing me money to maintain. Most of the content has moved to [https://bitfieldconsulting.com](https://bitfieldconsulting.com), if you'd like to read it.
